In [95]:
import pandas as pd 
##combines mvp list into one
df_trainmvp = pd.concat(map(pd.read_csv, ['mvp.csv', 'mvp2.csv']), ignore_index= True)
print(df_trainmvp)

    Year               MVP
0   1960  Wilt Chamberlain
1   1961      Bill Russell
2   1962      Bill Russell
3   1963      Bill Russell
4   1964   Oscar Robertson
..   ...               ...
95     0                 0
96     0                 0
97     0                 0
98     0                 0
99     0                 0

[100 rows x 2 columns]

In [96]:
import numpy as np 
import pathlib as Path
import os 
import glob
##combines all the player stat mvps from 1960 - 2010 (training data)
all_files = glob.glob("csvs/*.csv")
df_combinedcsv = pd.concat([pd.read_csv(f) for f in all_files], ignore_index = True)
df_withdrop = df_combinedcsv.drop_duplicates(keep='first', inplace=False, ignore_index=False)

In [97]:
##merges the mvp list with the statistics for the training data from 1960-2010
df_finaltrain = pd.merge(df_withdrop, df_trainmvp, on='Year')
print(df_finaltrain)
##change MVP to 1 and 0 to indicate if the person is the mvp or not - easier for model 

# length = len(df_finaltrain)
# num = 0
# for i in range(length):
#     if df_finaltrain.iat[i,2] == df_finaltrain.iat[i, 31]:
#         df_finaltrain.loc[df["MVP"] == df_finaltrain.iat[i, 31], "MVP"]= 1
#         num = num+1 
#     else: 
#         df_finaltrain['MVP'] = df_finaltrain['MVP'].replace([df_finaltrain.iat[i, 31]], 0)

##df_finaltrain.to_csv('testfile')
##print (df_finaltrain)

##print(num)

       Year   Rk           Player Pos Age   Tm   G   GS    MP    FG  ...  ORB  \
0      1960    1      Gary Alcorn   C  23  DET  58  NaN  11.6   1.6  ...  NaN
1      1960    2     Bob Anderegg  SF  22  NYK  33  NaN  11.3   1.7  ...  NaN
2      1960    3     Paul Arizin*  SF  31  PHW  72  NaN  36.4   8.2  ...  NaN
3      1960    4     Dick Barnett  SG  23  SYR  57  NaN  21.7   5.1  ...  NaN
4      1960    5    Elgin Baylor*  SF  25  MNL  70  NaN  41.0  10.8  ...  NaN
...     ...  ...              ...  ..  ..  ...  ..  ...   ...   ...  ...  ...
18474  2009  441    Julian Wright  SF  21  NOH  54   19  14.3   2.0  ...  0.9
18475  2009  442  Lorenzen Wright   C  33  CLE  17    2   7.4   0.6  ...  0.4
18476  2009  443       Nick Young  SG  23  WAS  82    5  22.4   4.1  ...  0.4
18477  2009  444   Thaddeus Young  PF  20  PHI  75   71  34.4   6.3  ...  1.9
18478  2009  445          Sun Yue  SG  23  LAL  10    0   2.8   0.3  ...  0.0

       DRB   TRB  AST  STL  BLK  TOV   PF   PTS               MVP
0      NaN   4.8  0.4  NaN  NaN  NaN  2.1   4.0  Wilt Chamberlain
1      NaN   2.1  0.9  NaN  NaN  NaN  1.0   4.0  Wilt Chamberlain
2      NaN   8.6  2.3  NaN  NaN  NaN  3.7  22.3  Wilt Chamberlain
3      NaN   2.7  2.8  NaN  NaN  NaN  1.7  12.4  Wilt Chamberlain
4      NaN  16.4  3.5  NaN  NaN  NaN  3.3  29.6  Wilt Chamberlain
...    ...   ...  ...  ...  ...  ...  ...   ...               ...
18474  2.0   2.8  0.8  0.6  0.4  0.8  0.9   4.4      LeBron James
18475  1.1   1.5  0.2  0.2  0.3  0.5  1.0   1.4      LeBron James
18476  1.5   1.8  1.2  0.5  0.2  1.1  1.7  10.9      LeBron James
18477  3.2   5.0  1.1  1.3  0.3  1.6  2.2  15.3      LeBron James
18478  0.0   0.0  0.2  0.1  0.1  0.3  1.0   0.6      LeBron James

[18479 rows x 32 columns]

In [98]:
##test data from 2010-2019 (includes mvp)
df_testmvp = pd.read_csv('testmvp.csv')
df_testmvp

   Year                    MVP
0  2010           LeBron James
1  2011           Derrick Rose
2  2012           LeBron James
3  2013           LeBron James
4  2014           Kevin Durant
5  2015          Stephen Curry
6  2016          Stephen Curry
7  2017      Russell Westbrook
8  2018           James Harden
9  2019  Giannis Antetokounmpo

In [99]:
##combines test statistics from 2010-2019 
all_testfiles = glob.glob("testcsvs/*.csv")
df_testcombinedcsv = pd.concat([pd.read_csv(f) for f in all_testfiles], ignore_index = True)
df_testwithdrop = df_testcombinedcsv.drop_duplicates(keep='first', inplace=False, ignore_index=False)
df_testwithdrop

,Year,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2010,1,Arron Afflalo,SG,24,DEN,82,75,27.1,3.3,...,.735,0.7,2.4,3.1,1.7,0.6,0.4,0.9,2.7,8.8
1,2010,2,Alexis Ajin√ßa,C,21,CHA,6,0,5.0,0.8,...,.000,0.2,0.5,0.7,0.0,0.2,0.2,0.3,0.8,1.7
2,2010,3,LaMarcus Aldridge,PF,24,POR,78,78,37.5,7.4,...,.757,2.5,5.6,8.0,2.1,0.9,0.6,1.3,3.0,17.9
3,2010,4,Joe Alexander,SF,23,CHI,8,0,3.6,0.1,...,.667,0.3,0.4,0.6,0.3,0.1,0.1,0.0,1.1,0.5
4,2010,5,Malik Allen,PF,31,DEN,51,3,8.9,0.9,...,.923,0.7,0.9,1.6,0.3,0.2,0.1,0.4,1.3,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6366,2019,528,Tyler Zeller,C,29,MEM,4,1,20.5,4.0,...,.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
6367,2019,529,Ante ≈Ωi≈æiƒá,C,22,CLE,59,25,18.3,3.1,...,.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
6368,2019,530,Ivica Zubac,C,21,TOT,59,37,17.6,3.6,...,.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
6369,2019,530,Ivica Zubac,C,21,LAL,33,12,15.6,3.4,...,.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
6370,2019,530,Ivica Zubac,C,21,LAC,26,25,20.2,3.8,...,.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

In [100]:
##merging the test data 
df_finaltest = pd.merge(df_testwithdrop, df_testmvp, on='Year')
df_finaltest

,Year,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,MVP
0,2010,1,Arron Afflalo,SG,24,DEN,82,75,27.1,3.3,...,0.7,2.4,3.1,1.7,0.6,0.4,0.9,2.7,8.8,LeBron James
1,2010,2,Alexis Ajin√ßa,C,21,CHA,6,0,5.0,0.8,...,0.2,0.5,0.7,0.0,0.2,0.2,0.3,0.8,1.7,LeBron James
2,2010,3,LaMarcus Aldridge,PF,24,POR,78,78,37.5,7.4,...,2.5,5.6,8.0,2.1,0.9,0.6,1.3,3.0,17.9,LeBron James
3,2010,4,Joe Alexander,SF,23,CHI,8,0,3.6,0.1,...,0.3,0.4,0.6,0.3,0.1,0.1,0.0,1.1,0.5,LeBron James
4,2010,5,Malik Allen,PF,31,DEN,51,3,8.9,0.9,...,0.7,0.9,1.6,0.3,0.2,0.1,0.4,1.3,2.1,LeBron James
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6139,2019,528,Tyler Zeller,C,29,MEM,4,1,20.5,4.0,...,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5,Giannis Antetokounmpo
6140,2019,529,Ante ≈Ωi≈æiƒá,C,22,CLE,59,25,18.3,3.1,...,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8,Giannis Antetokounmpo
6141,2019,530,Ivica Zubac,C,21,TOT,59,37,17.6,3.6,...,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,Giannis Antetokounmpo
6142,2019,530,Ivica Zubac,C,21,LAL,33,12,15.6,3.4,...,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5,Giannis Antetokounmpo
6143,2019,530,Ivica Zubac,C,21,LAC,26,25,20.2,3.8,...,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4,Giannis Antetokounmpo

In [101]:
##removing irrelevant columns in the dataset that do not affect if a player wins MVP - cleaning train data
##df_finaltrain['Mvp'] = np.where(df_finaltrain['Player'] == df_finaltrain['MVP'], 1, 0)
df_temptrain = df_finaltrain.drop(['Rk', 'Year', 'Pos', 'Age', 'Tm'], axis=1)
df_calculationstrain = df_temptrain.drop(['GS', 'DRB', 'ORB', 'PF'], axis=1)
print (df_calculationstrain)

                Player   G    MP    FG   FGA   FG%   3P  3PA   3P%    2P  ...  \
0          Gary Alcorn  58  11.6   1.6   5.4  .292  NaN  NaN   NaN   1.6  ...
1         Bob Anderegg  33  11.3   1.7   4.3  .385  NaN  NaN   NaN   1.7  ...
2         Paul Arizin*  72  36.4   8.2  19.4  .424  NaN  NaN   NaN   8.2  ...
3         Dick Barnett  57  21.7   5.1  12.3  .412  NaN  NaN   NaN   5.1  ...
4        Elgin Baylor*  70  41.0  10.8  25.4  .424  NaN  NaN   NaN  10.8  ...
...                ...  ..   ...   ...   ...   ...  ...  ...   ...   ...  ...
18474    Julian Wright  54  14.3   2.0   4.3  .466  0.0  0.4  .095   2.0  ...
18475  Lorenzen Wright  17   7.4   0.6   1.6  .370  0.0  0.0   NaN   0.6  ...
18476       Nick Young  82  22.4   4.1   9.2  .444  0.7  2.0  .341   3.4  ...
18477   Thaddeus Young  75  34.4   6.3  12.8  .495  0.7  2.2  .341   5.6  ...
18478          Sun Yue  10   2.8   0.3   1.1  .273  0.0  0.6  .000   0.3  ...

        FT   FTA   FT%   TRB  AST  STL  BLK  TOV   PTS               MVP
0      0.8   1.4  .571   4.8  0.4  NaN  NaN  NaN   4.0  Wilt Chamberlain
1      0.7   1.3  .548   2.1  0.9  NaN  NaN  NaN   4.0  Wilt Chamberlain
2      5.8   7.3  .798   8.6  2.3  NaN  NaN  NaN  22.3  Wilt Chamberlain
3      2.2   3.2  .711   2.7  2.8  NaN  NaN  NaN  12.4  Wilt Chamberlain
4      8.1  11.0  .732  16.4  3.5  NaN  NaN  NaN  29.6  Wilt Chamberlain
...    ...   ...   ...   ...  ...  ...  ...  ...   ...               ...
18474  0.3   0.6  .567   2.8  0.8  0.6  0.4  0.8   4.4      LeBron James
18475  0.2   0.5  .375   1.5  0.2  0.2  0.3  0.5   1.4      LeBron James
18476  2.0   2.4  .850   1.8  1.2  0.5  0.2  1.1  10.9      LeBron James
18477  1.9   2.5  .735   5.0  1.1  1.3  0.3  1.6  15.3      LeBron James
18478  0.0   0.0   NaN   0.0  0.2  0.1  0.1  0.3   0.6      LeBron James

[18479 rows x 23 columns]

In [102]:
##cleaning test data in the same way as above
##df_finaltest['Mvp'] = np.where(df_finaltest['Player'] == df_finaltest['MVP'], 1, 0)
df_temptest = df_finaltest.drop(['Rk', 'Year', 'Pos', 'Age', 'Tm'], axis=1)
df_calculationstest = df_temptest.drop(['GS', 'DRB', 'ORB', 'PF'], axis=1)
df_calculationstest

,Player,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,FT,FTA,FT%,TRB,AST,STL,BLK,TOV,PTS,MVP
0,Arron Afflalo,82,27.1,3.3,7.1,.465,1.3,3.0,.434,2.0,...,0.9,1.2,.735,3.1,1.7,0.6,0.4,0.9,8.8,LeBron James
1,Alexis Ajin√ßa,6,5.0,0.8,1.7,.500,0.0,0.0,NaN,0.8,...,0.0,0.2,.000,0.7,0.0,0.2,0.2,0.3,1.7,LeBron James
2,LaMarcus Aldridge,78,37.5,7.4,15.0,.495,0.1,0.2,.313,7.4,...,2.9,3.9,.757,8.0,2.1,0.9,0.6,1.3,17.9,LeBron James
3,Joe Alexander,8,3.6,0.1,0.8,.167,0.0,0.1,.000,0.1,...,0.3,0.4,.667,0.6,0.3,0.1,0.1,0.0,0.5,LeBron James
4,Malik Allen,51,8.9,0.9,2.3,.397,0.0,0.1,.167,0.9,...,0.2,0.3,.923,1.6,0.3,0.2,0.1,0.4,2.1,LeBron James
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6139,Tyler Zeller,4,20.5,4.0,7.0,.571,0.0,0.0,NaN,4.0,...,3.5,4.5,.778,4.5,0.8,0.3,0.8,1.0,11.5,Giannis Antetokounmpo
6140,Ante ≈Ωi≈æiƒá,59,18.3,3.1,5.6,.553,0.0,0.0,NaN,3.1,...,1.6,2.2,.705,5.4,0.9,0.2,0.4,1.0,7.8,Giannis Antetokounmpo
6141,Ivica Zubac,59,17.6,3.6,6.4,.559,0.0,0.0,NaN,3.6,...,1.7,2.1,.802,6.1,1.1,0.2,0.9,1.2,8.9,Giannis Antetokounmpo
6142,Ivica Zubac,33,15.6,3.4,5.8,.580,0.0,0.0,NaN,3.4,...,1.7,2.0,.864,4.9,0.8,0.1,0.8,1.0,8.5,Giannis Antetokounmpo
6143,Ivica Zubac,26,20.2,3.8,7.2,.538,0.0,0.0,NaN,3.8,...,1.7,2.3,.733,7.7,1.5,0.4,0.9,1.4,9.4,Giannis Antetokounmpo

In [108]:


num = 0
##remove parts of the data which have words in them randomly 

for i in range(len(df_calculationstrain.index) - 1):
    if df_calculationstrain.iloc[i, 0]  == 'Player':
        df_calculationstrain = df_calculationstrain.drop(i)
    if (df_calculationstrain.iloc[i, 0]) [len(df_calculationstrain.iloc[i, 0]) - 1] == "*":
        df_calculationstrain.iloc[i, 0] = (df_calculationstrain.iloc[i, 0]) [:-1]

##players that switched teams in the same season appear right next to each other so we need to make only one version of them 

df_calculationstrain.to_csv('lkfnsn.csv')

##print(num)
##print(df_calculationstrain.iloc[22,0])
##clean the data even more - delete duplicates of the same player/ delete the same rows

IndexError: index 18233 is out of bounds for axis 0 with size 18233

In [57]:
##using label encoding to encode two columns (Player + MVP) together - so that they both are based on the same numerical system 
## to give the model all numnerical data 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cols = ['Player', 'MVP']
df_calculationstrain[cols] = df_calculationstrain[cols].apply(LabelEncoder().fit_transform)
##df_calculationstrain['Player']=le.fit_transform(df_calculationstrain['Player'])
##df_calculationstrain['MVP']=le.fit_transform(df_calculationstrain['MVP'])


df_calculationstest[cols]= df_calculationstest[cols].apply(LabelEncoder().fit_transform)
##df_calculationstest['MVP']=le.fit_transform(df_calculationstest['MVP'])
##df_calculationstest

# df_calculationstest['Player']=le.fit_transform(df_calculationstest['Player'])
# df_calculationstest['MVP']=le.fit_transform(df_calculationstest['MVP'])
# df_calculationstest

In [11]:
##cleaning the data - converting all strings to float types (numbers in the dataframe were considered strings beforehand)
##ex: Games played was '87' not 87
##df_calculationstrain['G'] = df_calculationstrain['G'].astype(float)
##df_calculationstrain = df_calculationstrain.astype({ 'MP': 'float' })
for col in df_calculationstrain.columns: 
    df_calculationstrain[col]=pd.to_numeric(df_calculationstrain[col], errors='coerce')

for col in df_calculationstest.columns: 
    df_calculationstest[col]=pd.to_numeric(df_calculationstest[col], errors='coerce')

##converting the label encoding values to float64 from int64
##df_calculationstrain = df_calculationstrain.astype(float)
df_calculationstrain['Player'] = df_calculationstrain['Player'].astype(float)
df_calculationstrain['MVP'] = df_calculationstrain['MVP'].astype(float)
df_calculationstrain = df_calculationstrain.fillna(0)

df_calculationstest['Player'] = df_calculationstest['Player'].astype(float)
df_calculationstest['MVP'] = df_calculationstest['MVP'].astype(float)

##replace all null values with 0 
##null values exist because in the early years, some stats such as steals were not recorder by the NBA 
df_calculationstest = df_calculationstest.fillna(0)

In [21]:
##creating a decision tree model
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
##use the MVP column as the Y 
X_train = df_calculationstrain.drop(columns =['MVP'])
Y_train = df_calculationstrain['MVP']
X_test = df_calculationstest.drop(columns =['MVP'])
Y_test = df_calculationstest['MVP']
model = DecisionTreeClassifier()
##data = {'Name':[1,2,3],'Age':[21,22,23]}
##data2 = {'skill': [45, 46, 47]}
# dfX = pd.DataFrame(data)
# dfY = pd.DataFrame(data2)
model.fit(X_train,Y_train)
predictions = model.predict(X_test)
score = accuracy_score(Y_test, predictions)
print(score)

0.020670572916666668

In [104]:
for i in range(len(df_calculationstrain.index)):

    if df_calculationstrain.iloc[i,0] == df_calculationstrain.iloc[i,22]:
        df_calculationstrain['MVP'] = df_calculationstrain['MVP'].replace([df_calculationstrain.iloc[i,22]], 1)
        print('yes')

    else: 
        df_calculationstrain['MVP'] = df_calculationstrain['MVP'].replace([df_calculationstrain.iloc[i,22]], 0)
        
df_calculationstrain.to_csv('lasttest.csv')